# Learning outcomes
1.Gentle introduction to what is computer vision

2.Review: Important concepts of image stored as Numpy array

3.Image cropping (one of the data augmentation techniques employed in DL model training)

4.Split and merge image channels

5.Point operators (basic mathematical operations) /gamma correction
    *Aims: enhance/ reduce the contrast or illumination of the images
    
6.Image blending


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd './drive/MyDrive/mini project/week4'

/content/drive/MyDrive/mini project/week4


In [ ]:
import sys
assert sys.version_info >=(3,7)

import numpy as np
import cv2 as cv
from util_func import show_img

# Review: important concepts on the image arrays

images can be broadly categorized as **grayscale** and **color** images

|grayscale | color |

|matrix(2D array) | 3D array(channels)|

|(h,w)| (h,w,channels)|

In [ ]:
img = np.zeros((2,4),dtype = np.uint8)
print(img)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
img_bgr = cv.cvtColor(img,cv.COLOR_GRAY2BGR)
print(img_bgr)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
img[0,1] = 30
img[1,2] = 100
print(img)

[[  0  30   0   0]
 [  0   0 100   0]]


In [ ]:
img_bgr = cv.cvtColor(img,cv.COLOR_GRAY2BGR)
print(img_bgr)

[[[  0   0   0]
  [ 30  30  30]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [100 100 100]
  [  0   0   0]]]


# Accessing pixel elements


In [ ]:
#1st method

img = cv.imread("images/lena.jfif")

##[h,w,channel]
a = img[50,70,0]
b = img.item(50,70,0)
a == b

True

In [ ]:
#2nd method

%timeit a = img[50,70,0]
%timeit b = img.item(50,70,0)

178 ns ± 59.3 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
162 ns ± 49.2 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [3]:
# The takeaway the execution time is more or less the same. You are free to use either one

# Numpy

In [4]:
#extract the top left region of the image
yc, xc = img.shape[0]//2, img.shape[1]//2

topleft = img[:yc, :xc]

show_img("topleft", topleft)

NameError: ignored

In [ ]:
img

In [1]:
center = img[yc-30:yc+30, xc-30:xc+30]

show_img("Center", center)

NameError: ignored

In [2]:
#create a white image
white = np.zeros((200,200))+255
white = np.uint8(white)

show_img("White", white)

NameError: ignored

In [ ]:
#exercise
import matplotlib.pyplot as plt

image = np.ones((200,200,3),dtype = np.uint8)*255
plt.imshow(image)
plt.axis('off')
plt.show()

In [ ]:
patch = np.zeros((30,30), dtype = np.uint8)

patch[:10,10:20] = 255
patch[10:20,:10] = 255
patch[10:20,20:] = 255
patch[20:,10:20] = 255

img = np.tile(patch, (3,3))

show_img("img",img)

In [ ]:
#Q3
img = cv.imread("images/flower.jfif")

show_img("img", img)

In [ ]:
#1st way:
def select_rect(img,x,y,flgs,params):
    """mouseclick callback function"""
    if event == cv.EVENT_LBUTTONDOWN:
        print((x,y))
        cv.circle(img,(x,y),1,(0,0,255),-1)
        cv.imshow("img",img)

img = cv.imread("images/flower.jfif")
cv.imshow("img",img)
cv.setMouseCallback("img",select_rect)
cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
#2nd way:
bbox = cv.selectROI('flower_region',img)

In [ ]:
#3rd way:
# top left coordinates: (91,38) and bottom right coordinates: (170,120)
flower = img[38:120,91:170]

show_img("flower",flower)

# image cropping
in terms of operations, it is identical to slicing.

In [ ]:
##seperate image into diffirent width
img = cv.imread('images/dog.jfif')
img_copy = img.copy()

h, w = img.shape[:2]
n_vertical_grids = 3
n_horizontal_grids = 3

#to get the row and col sizes
M = int(h / n_vertical_grids)
N = int(w/ n_horizontal_grids)

for y in range(0, h, M):
    for x in range(0, w, N):
        x1 = x + M
        y1 = y + N

        if x1>=w and y1>=h:
                x1 = w-1
                y1 = h-1
                cv.rectangle(img_copy,(x,y),(x1,y1),(0,255,0),1)
                tile = img[y:h,x:w]
                tile.append(tile)

        elif y1>h:
            y1 = h-1
            cv.rectangle(img_copy,(x,y),(x1,y1),(0,255,0),1)
            tile = img[y:h,x:w]
            tile.append(tile)


        elif x1>w:
            x1 = w-1
            cv.rectangle(img_copy,(x,y),(x1,y1),(0,255,0),1)
            tile = img[y:h,x:w]
            tile.append(tile)

        else:
            cv.rectangle(img_copy, (x, y), (x1, y1), (0, 255, 0), 1)
            tile = img[y:h,x:w]
            tile.append(tile)

show_img('crop', img_copy)

In [ ]:
show_img("top right",tiles[2])

In [ ]:
#exercise
##Q1
img_array = np.zeros_like(img)

yc,xc = img.shape[0]//2, img.shape[1]//2

img_array[:yc,:xc] = img[yc:,xc:]
img_array[yc:,xc:] = img[:yc,:xc]
img_array[yc:,:xc] = img[:yc,xc:]
img_array[:yc,xc:] = img[yc:,:xc]

show_img("swap", img_array)

In [ ]:
##Q2 (h/w)


# Split and merge color channels

In [ ]:
b,g,r = cv.split(img)
img_merge = cv.merge((b,g,r))

In [ ]:
np.array_equal(img,img_merge)

In [ ]:
import matplatlib.pyplot as plt

In [ ]:
img = cv.imread("images/lena.jfif")
b,g,r = cv.split(img)

fig,(ax1,ax2,ax3) = plt.subplots(1,2,figsize=(12,4),sharey=True)
fig.suptitle("different color channels")
ax1.imshow(b,cmap=plt.cm.gray)
ax1.set(title="blue channel",xticks=[],yticks=[])
ax2.imshow(b,cmap=plt.cm.gray)
ax2.set(title="green channel",xticks=[],yticks=[])
ax3.imshow(b,cmap=plt.cm.gray)
ax3.set(title="red channel",xticks=[],yticks=[])

plt.tight_layout()
plt.show()

In [ ]:
#exercise (splitting and merging)
img = cv.imread("images/dog.jfif")

channels = cv.split(img)

colors = ("blue","green","red")

for i, mat in enumerate(channels):
    arr = np.zeros_like(img)
    arr[:,:,i] = mat
    imgs.append(arr)

for c,img in zip(colors,imgs):
    cv.imshow(c,img)

cv.waitKey(0)
cv.destroyAllWindows()

# Point operators

In [ ]:
np.array([-2,0,99,260],dtype = np.uint8)

In [ ]:
def point_op(img, alpha,beta):
    """point operators. Auguments
    1. Source image
    2. multiplier
    3. constant"""
    img = img.astype(float)
    res = alpha* img+beta
    res = np.clip(res, 0,255)
    res = np.uint8
    return res


In [ ]:
#increase the brightnss and and contrast the image
img = cv.imread("images/bridge.jfif")

transform = point_op(img,2,30)

cv.imshow("original",img)
show_img("transform",transform)

In [ ]:
transform2 = point_op(img,0.8,-20)

show_img("img_transform",transform2)

# Gamma Correction

In [ ]:
gamma = 1/2.2

lookUpTable = np.empty((1,256),dtype = np.uint8)
for i in range(256):
    lookUpTable[0,i] = np.clip(pow(i/255.0,gamma)*255,0,255)

img = cv.imread("images/mountains_prop.jpg")
res = cv.LUT(img,lookUpTable)

cv.nameWindow("original",cv.WINDOW_NORMAL)
cv.imshow("original",img)
show_img("gamma corrected", res, adjust = True)

# Image Blending (add 2 images)

In [ ]:
img = cv.imread("images/lena.jfif")
img2 = cv.imread("images/coins.jfif")

h,w = img.shape[:2]
img2 = cv.resize(img2,(w,h))

res = cv.addWeighted(img,alpha,img2,1-alpha,0)

cv.show("img1",img)
cv.show("img2",img2)
show_img("blending",res)


In [6]:
##Exercise (question1)

In [7]:
w = 400
h = 250

total_pixels = w * h
color_image = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8)
grayscale_image = np.random.randint(0, 256, (h, w), dtype=np.uint8)

cv.imshow("Color Image", color_image)
cv.waitKey(0)
cv.destroyAllWindows()


cv.imshow("Grayscale Image", grayscale_image, cmap='gray')
cv.waitKey(0)
cv.destroyAllWindows()


NameError: ignored

In [ ]:
##quetion 2

In [ ]:
def crop_grid(img, n_hor_grid, n_ver_grid, line_color):
    h, w, _ = img.shape
    patch_width = w // n_hor_grid
    patch_height = h // n_ver_grid

    image_with_grid = img.copy()

    for i in range(1, n_hor_grid):
        x = i * patch_width
        cv.line(image_with_grid, (x, 0), (x, h), line_color, 1)

    for i in range(1, n_ver_grid):
        y = i * patch_height
        cv.line(image_with_grid, (0, y), (w, y), line_color, 1)

    return image_with_grid

img = cv.imread("image.jpg")

n_hor_grid = 4
n_ver_grid = 3
line_color = (0, 255, 0)

image_with_grid = crop_grid(img, n_hor_grid, n_ver_grid, line_color)

cv.imshow("Image with Grid", image_with_grid)
cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
##question 3

In [ ]:
def image_blend(img1, img2, alpha):
    blended_img = cv.addWeighted(img1, alpha, img2, 1 - alpha, 0)
    return blended_img


img1 = cv.imread("images/lena.jfif")
img2 = cv.imread("images/coins.jfif")

num_frames = 10
alpha_values = [i / (num_frames - 1) for i in range(num_frames)]

for alpha in alpha_values:
    blended_image = image_blend(img1, img2, alpha)
    cv.imshow("Blended Image", blended_image)
    cv.waitKey(1000)  # Display each frame for 1 second
    cv.destroyAllWindows()


In [ ]:
## question 4

In [ ]:
def apply_watermark(image_path, watermark_path, output_path):
    image = cv.imread(image_path)
    watermark = cv.imread(watermark_path, cv.IMREAD_UNCHANGED)
    watermark = cv.resize(watermark, (image.shape[1], image.shape[0]))

    overlay = np.zeros_like(image)
    overlay[image.shape[0] - watermark.shape[0]:image.shape[0], image.shape[1] - watermark.shape[1]:image.shape[1]] = watermark

    watermarked_image = cv.addWeighted(image, 1, overlay, 1, 0)

    cv.imwrite(output_path, watermarked_image)

image_path = "travel_hd.jpg"
watermark_path = "watermark.png"
output_path = "watermarked_image.jpg"

apply_watermark(image_path, watermark_path, output_path)

print("Watermark applied successfully!")
